#!/usr/bin/env python3
"""Generate service wire policy. Canonical source: ottplay-unification/contracts.
Copies in consumers are generated distribution tooling; never maintain them there.
--check works offline in each shipping consumer with Python 3 and (for Go) gofmt.
"""
import argparse
import hashlib
import json
import pathlib
import subprocess
import sys

SCRIPT = pathlib.Path(__file__).resolve()
ROOT = SCRIPT.parent.parent
SCHEMA = ROOT / "contracts/ottplay-wire-v1.json"


def ts_source(s, digest):
    lines = ["// Generated by ottplay-unification; do not edit.",
             "// Wire schema v1 SHA-256: " + digest, ""]
    for name, fields in s["interfaces"].items():
        lines.append("export interface " + name + " {")
        lines += ["    " + k + ": " + v + ";" for k, v in fields.items()]
        lines += ["}", ""]
    lines.append("export const wire = {")
    for k, v in sorted(s["constants"].items()):
        lines.append("    " + k + ": " + json.dumps(v) + ",")
    lines += ["};", "", "const wireDeviceIdPattern = new RegExp(wire.deviceIdPattern);",
              "const wireDeviceTokenPattern = new RegExp(wire.tokenPattern);",
              "const wireCommandIdPattern = new RegExp(wire.clientCommandIdPattern);",
              "const wireSwopClientIdPattern = new RegExp(wire.swopClientIdPattern);", "",
              "export function validDeviceId(value: string): boolean {",
              "    return wireDeviceIdPattern.test(value);", "}", "",
              "export function validDeviceToken(value: string): boolean {",
              "    return wireDeviceTokenPattern.test(value);", "}", "",
              "export function validSwopClientId(value: string): boolean {",
              "    return wireSwopClientIdPattern.test(value);", "}", "",
              "export function validCommandEnvelope(data: any): boolean {",
              "    if (!data || !Array.isArray(data.commands)) return false;",
              "    if (data.commands.length > wire.commandEnvelopeMax) return false;",
              "    for (var i = 0; i < data.commands.length; i++) {",
              "        var item = data.commands[i];",
              '        if (!item || typeof item !== "object") return false;',
              '        if (typeof item.id !== "string" || !wireCommandIdPattern.test(item.id))',
              "            return false;", "    }", "    return true;", "}", "",
              "function wireFinite(value: any): boolean {",
              '    return typeof value === "number" && isFinite(value);', "}", "",
              "function wireInteger(value: any, minimum: number): boolean {",
              "    return wireFinite(value) && Math.floor(value) === value && value >= minimum;",
              "}", "", "export function validPlayerCommand(cmd: any): boolean {",
              '    if (!(cmd && typeof cmd.command === "string")) return false;']
    for name, f in s["fields"].items():
        v="cmd."+name; p=f["player"]; kind=f["type"]
        if kind=="text": expr='typeof '+v+' !== "string"'
        elif kind=="integer": expr='!wireInteger('+v+', '+str(p['min'])+')'
        elif kind=="range":
            expr='!Array.isArray('+v+') ||\n'+v+'.length !== 2 ||\n!wireInteger('+v+'[0], '+str(p['min'])+') ||\n!wireInteger('+v+'[1], '+str(p['min'])+') ||\n'+v+'[0] > '+v+'[1]'
        else:
            expr='!wireFinite('+v+')'
            if 'exclusiveMin' in p: expr+=' ||\n'+v+' <= '+str(p['exclusiveMin'])
            if 'max' in p: expr+=' ||\n'+v+' > '+str(p['max'])
        lines += ['    if ('+v+' !== undefined) {']
        if '\n' not in expr:
            lines += ['        if ('+expr+') return false;']
        else:
            lines += ['        if (']
            lines += ['            '+part for part in expr.split('\n')]
            lines += ['        )','            return false;']
        lines += ['    }']
    lines += ['    return true;', '}', '']
    lines += ["export function commandEndpointBase(path: string): string {",
              "    var paths = [wire.commandPath, wire.legacyPollPath, wire.legacyNotifyPath];",
              "    for (var i = 0; i < paths.length; i++) {",
              "        if (path.slice(-paths[i].length) === paths[i])",
              "            return path.slice(0, -paths[i].length);",
              "    }", "    return path;", "}", ""]
    return '\n'.join(lines)


def go_constants(s,digest):
    lines=['// Code generated by ottplay-unification; DO NOT EDIT.', '// Wire schema v1 SHA-256: '+digest,'package wire','const (']
    for k,v in s['constants'].items():
        lines.append(k[0].upper()+k[1:]+' = '+json.dumps(v))
    return gofmt('\n'.join(lines+[')']))


def gofmt(source):
    return subprocess.run(['gofmt'],input=source,text=True,check=True,capture_output=True).stdout


def go_commands(s,digest):
    lines=['// Code generated by ottplay-unification; DO NOT EDIT.', '// Wire schema v1 SHA-256: '+digest,'package control','import ("encoding/json";"errors";"math")',
    'type wireField struct { kind string; minimum, maximum float64; maxBytes int; primitive string }',
    'var wireFields = map[string]wireField{']
    for n,f in s['fields'].items():
        p=f['server'];lines.append(json.dumps(n)+': {'+', '.join([json.dumps(f['type']),str(p.get('min','-math.MaxFloat64')),str(p.get('max','math.MaxFloat64')),str(p.get('maxBytes',0)),json.dumps(p.get('primitive',''))])+'},')
    lines += ['}', 'type wireCommand struct { required, optional, exactlyOne []string }','var wireCommands = map[string]wireCommand{']
    for n,c in s['commands'].items():
        lines.append(json.dumps(n)+': {'+', '.join('[]string{'+','.join(json.dumps(v) for v in c.get(k,[]))+'}' for k in ['required','optional','exactlyOne'])+'},')
    e=s['profiles']['controlServer']['errors']
    lines+=['}', '''func validWireField(v json.RawMessage, rule wireField) bool {
 switch rule.kind {
 case "number", "integer": return numberValue(v, rule.minimum, rule.maximum, rule.kind == "integer")
 case "text":
  value, ok := textValue(v, rule.maxBytes)
  if !ok { return false }
  switch rule.primitive { case "json": return json.Valid([]byte(value)); case "httpUrl": return wireHTTPURL(value) }
  return true
 case "range":
  var values []json.RawMessage
  if json.Unmarshal(v, &values) != nil || len(values) != 2 || !numberValue(values[0], rule.minimum, rule.maximum, true) || !numberValue(values[1], rule.minimum, rule.maximum, true) { return false }
  var lo, hi float64; _ = json.Unmarshal(values[0], &lo); _ = json.Unmarshal(values[1], &hi); return lo <= hi
 }
 return false
}
func validateCommand(body []byte) (map[string]json.RawMessage, error) {
 m, err := decodeObject(body); if err != nil { return nil, err }
 cmd, ok := textValue(m["command"], COMMANDMAX)
 if !ok { return nil, errors.New(COMMANDERROR) }
 policy, ok := wireCommands[cmd]
 if !ok { return nil, errors.New(UNSUPPORTEDERROR) }
 allowed := map[string]bool{"command": true}
 valid := true
 for _, key := range policy.required { allowed[key] = true; valid = validWireField(m[key], wireFields[key]) && valid }
 for _, key := range policy.optional { allowed[key] = true; if value, exists := m[key]; exists { valid = validWireField(value, wireFields[key]) && valid } }
 if len(policy.exactlyOne) > 0 { count := 0; for _, key := range policy.exactlyOne { if _, exists := m[key]; exists { count++ } }; valid = valid && count == 1 }
 for key := range m { if !allowed[key] { return nil, errors.New(UNEXPECTEDERROR) } }
 if !valid { return nil, errors.New(VALUEERROR) }; return m, nil
}'''.replace('COMMANDMAX',str(s['profiles']['controlServer']['commandMaxBytes'])).replace('COMMANDERROR',json.dumps(e['command'])).replace('UNSUPPORTEDERROR',json.dumps(e['unsupported'])).replace('UNEXPECTEDERROR',json.dumps(e['unexpected'])).replace('VALUEERROR',json.dumps(e['value']))]
    return gofmt('\n'.join(lines))


def outputs(target,s,digest):
    if target=='main': return {'src/shared/wire-contracts.ts':ts_source(s,digest)}
    if target=='swop': return {'src/wire-contracts.ts':ts_source(s,digest)}
    return {'internal/wire/contracts.gen.go':go_constants(s,digest),'internal/control/wire_commands.gen.go':go_commands(s,digest)}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--target',choices=['main','swop','control']);args=parser.parse_args()
    raw=SCHEMA.read_bytes();s=json.loads(raw);assert s['version']==1;digest=hashlib.sha256(raw).hexdigest()
    receipt_path=ROOT/'contracts/wire-source.json'
    local_receipt=json.loads(receipt_path.read_text()) if receipt_path.exists() else None
    selected=args.target or (local_receipt['target'] if local_receipt else None)
    generator_digest=hashlib.sha256(SCRIPT.read_bytes()).hexdigest()
    targets=[(selected,ROOT)] if selected else [('main',ROOT/'ottplay-foss'),('swop',ROOT/'ottplay-swop'),('control',ROOT/'ottplay-control-server')]
    bad=[]
    if local_receipt and (local_receipt['schemaSha256'] != digest or local_receipt['generatorSha256'] != generator_digest or local_receipt['target'] != selected):
        sys.exit('Wire source receipt differs: redistribute from canonical source')
    for target,base in targets:
        files={k:v.encode() for k,v in outputs(target,s,digest).items()}
        if not selected:
            files['contracts/ottplay-wire-v1.json']=raw;files['scripts/generate-wire-contracts.py']=SCRIPT.read_bytes()
            receipt={'version':1,'target':target,'schemaSha256':digest,'generatorSha256':generator_digest}
            files['contracts/wire-source.json']=(json.dumps(receipt,indent=2)+'\n').encode()
        for rel,value in files.items():
            dest=base/rel
            if args.check:
                if not dest.exists() or dest.read_bytes()!=value:bad.append(str(dest))
            else:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(value)
    if bad:sys.exit('Generated wire contracts differ:\n'+'\n'.join(bad))
    print(('Checked' if args.check else 'Generated')+' wire v1 '+digest+' ('+', '.join(t for t,_ in targets)+')')

if __name__=='__main__':main()
