// Generated by ottplay-unification; do not edit.
// Wire schema v1 SHA-256: 23a19dae2cb07334edadb2cb938749303dd44f0e81ad205352aa2a049c5b6ca4

export interface Command {
    channel_name?: string;
    channel_number?: number;
    command: string;
    message?: string;
    playlist?: string;
    popup_duration?: number;
    provider?: number;
    provider_settings?: string;
    random_range?: [number, number];
    volume?: number;
    volume_step?: number;
}

export interface SwopSessionResponse {
    code?: string;
    error?: string;
    expiresIn?: number;
    url?: string;
}

export interface SwopValueResponse {
    error?: string;
    status?: string;
    value?: string;
}

export const wire = {
    ackBatchMax: 50,
    ackPath: "/api/webhook/commands/ack",
    clientCommandIdPattern: "^[A-Za-z0-9_-]{1,128}$",
    commandEnvelopeMax: 256,
    commandPath: "/api/webhook/commands",
    deviceIdPattern: "^[A-Za-z0-9._:-]{1,128}$",
    legacyNotifyPath: "/webhook/notify",
    legacyPollPath: "/webhook/poll",
    serverCommandIdPattern: "^[0-9a-f]{32}$",
    swopCaptionLimit: 200,
    swopClientHeader: "X-Swop-Client-Id",
    swopClientIdPattern: "^[A-Za-z0-9._:-]{8,128}$",
    swopCodeAlphabet: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
    swopCodeLength: 6,
    swopDefaultTtl: 600,
    swopDraftLimit: 4000,
    swopFallbackClientHeader: "X-Ottplay-Client-Id",
    swopNoteLimit: 200,
    swopSessionPath: "/session",
    swopSubmitPath: "/submit",
    swopValueLimit: 8000,
    swopValuePath: "/val",
    tokenPattern: "^[A-Za-z0-9_-]{32,256}$",
};

const wireDeviceIdPattern = new RegExp(wire.deviceIdPattern);
const wireDeviceTokenPattern = new RegExp(wire.tokenPattern);
const wireCommandIdPattern = new RegExp(wire.clientCommandIdPattern);
const wireSwopClientIdPattern = new RegExp(wire.swopClientIdPattern);

export function validDeviceId(value: string): boolean {
    return wireDeviceIdPattern.test(value);
}

export function validDeviceToken(value: string): boolean {
    return wireDeviceTokenPattern.test(value);
}

export function validSwopClientId(value: string): boolean {
    return wireSwopClientIdPattern.test(value);
}

export function validCommandEnvelope(data: any): boolean {
    if (!data || !Array.isArray(data.commands)) return false;
    if (data.commands.length > wire.commandEnvelopeMax) return false;
    for (var i = 0; i < data.commands.length; i++) {
        var item = data.commands[i];
        if (!item || typeof item !== "object") return false;
        if (typeof item.id !== "string" || !wireCommandIdPattern.test(item.id))
            return false;
    }
    return true;
}

function wireFinite(value: any): boolean {
    return typeof value === "number" && isFinite(value);
}

function wireInteger(value: any, minimum: number): boolean {
    return wireFinite(value) && Math.floor(value) === value && value >= minimum;
}

export function validPlayerCommand(cmd: any): boolean {
    if (!(cmd && typeof cmd.command === "string")) return false;
    if (cmd.popup_duration !== undefined) {
        if (
            !wireFinite(cmd.popup_duration) ||
            cmd.popup_duration <= 0 ||
            cmd.popup_duration > 3600
        )
            return false;
    }
    if (cmd.channel_number !== undefined) {
        if (!wireInteger(cmd.channel_number, 1)) return false;
    }
    if (cmd.provider !== undefined) {
        if (!wireInteger(cmd.provider, 0)) return false;
    }
    if (cmd.volume !== undefined) {
        if (!wireFinite(cmd.volume)) return false;
    }
    if (cmd.volume_step !== undefined) {
        if (!wireFinite(cmd.volume_step)) return false;
    }
    if (cmd.random_range !== undefined) {
        if (
            !Array.isArray(cmd.random_range) ||
            cmd.random_range.length !== 2 ||
            !wireInteger(cmd.random_range[0], 1) ||
            !wireInteger(cmd.random_range[1], 1) ||
            cmd.random_range[0] > cmd.random_range[1]
        )
            return false;
    }
    if (cmd.channel_name !== undefined) {
        if (typeof cmd.channel_name !== "string") return false;
    }
    if (cmd.message !== undefined) {
        if (typeof cmd.message !== "string") return false;
    }
    if (cmd.playlist !== undefined) {
        if (typeof cmd.playlist !== "string") return false;
    }
    if (cmd.provider_settings !== undefined) {
        if (typeof cmd.provider_settings !== "string") return false;
    }
    return true;
}

export function commandEndpointBase(path: string): string {
    var paths = [wire.commandPath, wire.legacyPollPath, wire.legacyNotifyPath];
    for (var i = 0; i < paths.length; i++) {
        if (path.slice(-paths[i].length) === paths[i])
            return path.slice(0, -paths[i].length);
    }
    return path;
}
